-- Migration: Add text columns to candidate_resume_optimizations
-- Run this in your Supabase SQL Editor AFTER the initial table creation.

-- Store the verbatim original resume text (same source used for ATS screening).
-- This is extracted from the uploaded PDF/DOCX and is NEVER modified.
ALTER TABLE public.candidate_resume_optimizations
    ADD COLUMN IF NOT EXISTS original_resume_text TEXT,
    ADD COLUMN IF NOT EXISTS optimized_text       TEXT,   -- All AI changes applied
    ADD COLUMN IF NOT EXISTS final_resume_text    TEXT;   -- Only recruiter-accepted changes applied

-- Drop the old structured-JSON columns that are no longer used
-- (resume_parsed_data was the display-only representation, not the optimization source)
ALTER TABLE public.candidate_resume_optimizations
    DROP COLUMN IF EXISTS optimized_resume;

COMMENT ON COLUMN public.candidate_resume_optimizations.original_resume_text IS
    'Verbatim raw text extracted from the candidate''s uploaded PDF/DOCX. '
    'This is the same source used for ATS screening. NEVER modified.';

COMMENT ON COLUMN public.candidate_resume_optimizations.optimized_text IS
    'Resume text with ALL AI-suggested changes applied (draft version).';

COMMENT ON COLUMN public.candidate_resume_optimizations.final_resume_text IS
    'Resume text with ONLY the recruiter-approved changes applied. '
    'Set when the recruiter clicks Finalize.';

ALTER TABLE public.candidate_resume_optimizations
    ADD COLUMN IF NOT EXISTS gap_cautions JSONB DEFAULT '[]'::jsonb;

COMMENT ON COLUMN public.candidate_resume_optimizations.gap_cautions IS
    'Array of employment gap cautions generated by the AI.';
