"""
Resume Optimizer Service
========================
Uses the candidate's raw resume_text (extracted from their uploaded PDF/DOCX)
as the ONLY source of truth for AI optimization.

The structured resume_parsed_data is NOT used here — it is a display-only
representation generated by a separate AI parser and must not be treated as
the authoritative resume content.

Produces:
  - A list of text-level changes (verbatim original → improved replacement)
  - Before / After ATS score estimates
  - An optimized_text string (original resume_text with accepted changes applied)
  - Document exports (DOCX + PDF) generated from the optimized_text
"""
from __future__ import annotations

import io
import logging
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


class ResumeOptimizerService:
    """
    Orchestrates AI resume content optimization.

    Works exclusively on raw resume text. Never modifies formatting,
    layout, fonts, bullet styles, or spacing — only content.
    """

    def __init__(self):
        from app.services.ai.factory import get_ai
        self._ai = get_ai()

    # ------------------------------------------------------------------
    # Main optimization entry point
    # ------------------------------------------------------------------

    async def optimize(
        self,
        resume_text: str,
        job: Dict[str, Any],
        screening_analysis: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Analyze the raw resume text against the JD and return improvements.

        Args:
            resume_text:        The raw text extracted from the candidate's original
                                uploaded PDF/DOCX. This is the ONLY source used.
            job:                The job description dict (title, role, description,
                                must_have_skills, good_to_have_skills).
            screening_analysis: The ats_screenings row for gap context (optional).

        Returns:
            {
                optimization_summary: str,
                before_score: int,
                after_score: int,
                changes: [OptimizationChange],
                optimized_text: str  — full resume text with all changes applied
            }
        """
        from app.prompts.resume_optimization import get_resume_optimization_prompt
        import uuid

        what_lacks: List[str] = []
        whats_good: List[str] = []
        before_score = 0
        if isinstance(screening_analysis, dict):
            detailed = screening_analysis.get("detailed_analysis") or {}
            what_lacks = detailed.get("what_lacks") or []
            whats_good = detailed.get("whats_good") or []
            before_score = int(screening_analysis.get("overall_score") or 0)

        system_prompt, user_prompt = get_resume_optimization_prompt(
            resume_text=resume_text,
            job_title=job.get("title", ""),
            job_role=job.get("role", ""),
            job_description=job.get("description", ""),
            must_have_skills=job.get("must_have_skills") or [],
            good_to_have_skills=job.get("good_to_have_skills") or [],
            what_lacks=what_lacks,
            whats_good=whats_good,
            before_score=before_score,
            after_score_example=min(100, before_score + 12),
        )

        try:
            result = await self._ai.generate_json(
                user_prompt,
                system_instruction=system_prompt,
                temperature=0.35,
                max_tokens=6000,
                timeout_s=90,
            )
        except Exception as exc:
            logger.error("[ResumeOptimizer] AI call failed: %s", exc)
            raise RuntimeError("AI optimization failed. Please try again.") from exc

        # Normalize changes — assign UUIDs, validate verbatim originals
        changes = []
        gap_cautions = result.get("gap_cautions") or []
        for ch in result.get("changes") or []:
            if not isinstance(ch, dict):
                continue
            original = ch.get("original", "")
            improved = ch.get("improved", "")
            change_type = ch.get("change_type", "wording")

            # Gap cautions should be in gap_cautions array, but handle if AI puts them here
            if change_type == "gap_caution":
                gap_cautions.append({"reason": ch.get("reason", "")})
                continue

            # For all real changes: the original MUST be found verbatim in the resume.
            # We try exact match first, then whitespace-normalized match.
            if original:
                if original not in resume_text:
                    # Try normalizing whitespace in both
                    import re
                    norm_original = re.sub(r'\s+', ' ', original.strip())
                    norm_resume = re.sub(r'\s+', ' ', resume_text)
                    if norm_original not in norm_resume:
                        logger.warning(
                            "[ResumeOptimizer] Skipping change — original text not found in resume: %r",
                            original[:120],
                        )
                        continue
            else:
                # Empty original — skip (can't do a replacement without original)
                continue

            changes.append({
                "change_id": ch.get("change_id") or str(uuid.uuid4()),
                "section": ch.get("section", ""),
                "section_label": ch.get("section_label", ch.get("section", "").replace("_", " ").title()),
                "original": original,
                "improved": improved,
                "reason": ch.get("reason", ""),
                "change_type": change_type,
                "score_impact": int(ch.get("score_impact") or 0),
            })

        # Recalculate after_score from actual validated changes (never trust AI's after_score)
        total_impact = sum(c["score_impact"] for c in changes)
        computed_after_score = min(100, before_score + total_impact)

        # Build optimized_text (all changes applied to the original)
        optimized_text = self._apply_changes(resume_text, changes)

        return {
            "optimization_summary": result.get("optimization_summary", ""),
            "before_score": before_score,
            "after_score": computed_after_score,
            "changes": changes,
            "gap_cautions": gap_cautions,
            "optimized_text": optimized_text,
        }

    # ------------------------------------------------------------------
    # Apply a subset of changes to produce the final text
    # ------------------------------------------------------------------

    @staticmethod
    def apply_accepted_changes(resume_text: str, changes: List[Dict], accepted_ids: List[str]) -> str:
        """
        Apply only the accepted changes to the original resume text.
        Each change is a verbatim find-and-replace on the text.
        """
        accepted_set = set(accepted_ids)
        result = resume_text
        for ch in changes:
            if ch.get("change_id") not in accepted_set:
                continue
            original = ch.get("original", "")
            improved = ch.get("improved", "")
            change_type = ch.get("change_type", "")
            # Skip gap cautions and empty originals
            if change_type == "gap_caution" or not original or not improved:
                continue
            if original in result:
                result = result.replace(original, improved, 1)
        return result

    @staticmethod
    def synchronize_candidate_details(resume_text: str, candidate_profile: Dict[str, Any]) -> str:
        """
        Keep the optimized resume aligned with canonical candidate details shown in UI.

        Ensures top-of-resume identity/contact uses the candidate record (with tenant overrides).
        """
        import re

        text = str(resume_text or "").replace("\r\n", "\n").replace("\r", "\n")
        lines = text.split("\n")

        def _clean(v: Any) -> str:
            return str(v or "").strip()

        full_name = _clean(candidate_profile.get("full_name"))
        email = _clean(candidate_profile.get("email"))
        phone = _clean(candidate_profile.get("phone"))
        location = _clean(candidate_profile.get("location"))
        portfolio = _clean(candidate_profile.get("portfolio_url"))
        github = _clean(candidate_profile.get("github_url"))
        linkedin = _clean(candidate_profile.get("linkedin_url"))

        # Build contact info line
        contact_parts = []
        if email:
            contact_parts.append(email)
        if phone:
            contact_parts.append(phone)
        if location:
            contact_parts.append(location)
        
        # Build links line separately for cleaner formatting
        link_parts = []
        if linkedin:
            link_parts.append(linkedin)
        if portfolio:
            link_parts.append(portfolio)
        if github:
            link_parts.append(github)

        # Remove noisy auto-generated header/contact lines from the first block.
        body_lines: List[str] = []
        skip_patterns = ["@", "linkedin", "github.com", "http://", "https://", "portfolio"]
        for idx, line in enumerate(lines):
            stripped = line.strip()
            if idx <= 10:
                # Skip lines that look like name/contact info
                if full_name and stripped.lower() == full_name.lower():
                    continue
                if stripped and any(tok in stripped.lower() for tok in skip_patterns):
                    continue
                if phone and re.sub(r"\D", "", phone) and re.sub(r"\D", "", phone) in re.sub(r"\D", "", stripped):
                    continue
                # Skip lines that are just contact info separators
                if stripped and "|" in stripped and len(stripped.split("|")) >= 2:
                    has_contact = any(p.lower() in stripped.lower() for p in [email, phone] if p)
                    if has_contact:
                        continue
            body_lines.append(line)

        # Trim leading empty lines after header cleanup.
        while body_lines and not body_lines[0].strip():
            body_lines.pop(0)

        # Assemble clean header
        assembled: List[str] = []
        if full_name:
            assembled.append(full_name)
        if contact_parts:
            assembled.append(" | ".join(contact_parts))
        if link_parts:
            assembled.append(" | ".join(link_parts))
        if assembled:
            assembled.append("")  # Blank line after header
        assembled.extend(body_lines)

        synced = "\n".join(assembled).strip()
        return ResumeOptimizerService.to_ats_friendly_text(synced)

    @staticmethod
    def to_ats_friendly_text(resume_text: str) -> str:
        """
        Normalize raw resume text into a consistent ATS-friendly plain-text structure.
        
        Produces clean, well-structured text with:
        - Standardized section headers
        - Consistent bullet formatting
        - Proper spacing between sections
        - Clean line breaks
        """
        import re

        text = str(resume_text or "").replace("\r\n", "\n").replace("\r", "\n")
        lines = text.split("\n")

        # Comprehensive section header mappings
        section_aliases = {
            # Summary variations
            "summary": "PROFESSIONAL SUMMARY",
            "professional summary": "PROFESSIONAL SUMMARY",
            "executive summary": "PROFESSIONAL SUMMARY",
            "career summary": "PROFESSIONAL SUMMARY",
            "profile": "PROFESSIONAL SUMMARY",
            "about me": "PROFESSIONAL SUMMARY",
            "objective": "CAREER OBJECTIVE",
            "career objective": "CAREER OBJECTIVE",
            
            # Skills variations
            "skills": "TECHNICAL SKILLS",
            "technical skills": "TECHNICAL SKILLS",
            "core skills": "TECHNICAL SKILLS",
            "key skills": "TECHNICAL SKILLS",
            "competencies": "TECHNICAL SKILLS",
            "core competencies": "TECHNICAL SKILLS",
            "technologies": "TECHNICAL SKILLS",
            "tools & technologies": "TECHNICAL SKILLS",
            "technical proficiencies": "TECHNICAL SKILLS",
            
            # Experience variations
            "experience": "PROFESSIONAL EXPERIENCE",
            "work experience": "PROFESSIONAL EXPERIENCE",
            "professional experience": "PROFESSIONAL EXPERIENCE",
            "employment history": "PROFESSIONAL EXPERIENCE",
            "work history": "PROFESSIONAL EXPERIENCE",
            "career history": "PROFESSIONAL EXPERIENCE",
            
            # Projects
            "projects": "PROJECTS",
            "key projects": "PROJECTS",
            "personal projects": "PROJECTS",
            "notable projects": "PROJECTS",
            
            # Education
            "education": "EDUCATION",
            "academic background": "EDUCATION",
            "educational background": "EDUCATION",
            "qualifications": "EDUCATION",
            
            # Certifications
            "certifications": "CERTIFICATIONS",
            "certificates": "CERTIFICATIONS",
            "professional certifications": "CERTIFICATIONS",
            "licenses & certifications": "CERTIFICATIONS",
            
            # Achievements
            "achievements": "ACHIEVEMENTS",
            "accomplishments": "ACHIEVEMENTS",
            "awards": "AWARDS & ACHIEVEMENTS",
            "awards & achievements": "AWARDS & ACHIEVEMENTS",
            "honors": "AWARDS & ACHIEVEMENTS",
            
            # Additional sections
            "publications": "PUBLICATIONS",
            "languages": "LANGUAGES",
            "interests": "INTERESTS",
            "hobbies": "INTERESTS",
            "references": "REFERENCES",
            "volunteer": "VOLUNTEER EXPERIENCE",
            "volunteer experience": "VOLUNTEER EXPERIENCE",
        }

        out: List[str] = []
        blank_streak = 0
        in_header_block = True  # Track if we're still in the name/contact header
        header_line_count = 0

        for idx, raw in enumerate(lines):
            stripped = raw.strip()
            
            # Handle blank lines
            if not stripped:
                blank_streak += 1
                # Allow max 1 blank line between content
                if blank_streak <= 1 and out and out[-1] != "":
                    out.append("")
                continue

            blank_streak = 0
            normalized = re.sub(r"\s+", " ", stripped)
            key = normalized.lower().rstrip(":")
            mapped_header = section_aliases.get(key)

            # Detect section headers
            is_section_header = bool(mapped_header)
            if not is_section_header:
                # Check if it looks like a header (short, uppercase, no bullet)
                is_section_header = (
                    len(normalized) <= 45
                    and normalized.upper() == normalized
                    and not normalized.startswith(("-", "•", "*", "–", "·"))
                    and not any(c.isdigit() for c in normalized[:3])  # Avoid dates
                    and not normalized.endswith((",", ";", "."))
                    and len(normalized.split()) <= 5  # Max 5 words for headers
                )

            # First section header ends the header block
            if is_section_header and in_header_block:
                in_header_block = False

            # Handle header block (name, contact info)
            if in_header_block and idx <= 5:
                header_line_count += 1
                out.append(normalized)
                if header_line_count >= 3:  # After 3 header lines, add spacing
                    in_header_block = False
                continue

            if is_section_header:
                header_text = mapped_header or normalized.upper().rstrip(":")
                # Ensure blank line before section header
                if out and out[-1] != "":
                    out.append("")
                out.append(header_text)
                continue

            # Handle bullet points - normalize to consistent format
            if normalized.startswith(("•", "-", "*", "–", "·", ">", "►", "▪", "○")):
                bullet_content = re.sub(r"^[•\-*–·>►▪○]+\s*", "", normalized).strip()
                if bullet_content:
                    out.append(f"• {bullet_content}")
            else:
                out.append(normalized)

        # Clean up trailing empty lines
        while out and not out[-1]:
            out.pop()
            
        # Clean up leading empty lines
        while out and not out[0]:
            out.pop(0)
            
        return "\n".join(out)

    @staticmethod
    def _apply_changes(resume_text: str, changes: List[Dict]) -> str:
        """Apply ALL actionable changes to produce a fully optimized text."""
        result = resume_text
        for ch in changes:
            original = ch.get("original", "")
            improved = ch.get("improved", "")
            change_type = ch.get("change_type", "")
            if change_type == "gap_caution" or not original or not improved:
                continue
            if original in result:
                result = result.replace(original, improved, 1)
        return result

    # ------------------------------------------------------------------
    # Document generation — from plain text
    # ------------------------------------------------------------------

    async def generate_docx(
        self,
        resume_text: str,
        candidate_name: str,
        job_title: str,
        resume_url: Optional[str] = None,
        changes: Optional[List[Dict]] = None,
        accepted_ids: Optional[List[str]] = None
    ) -> bytes:
        """
        Generate a professional ATS-friendly DOCX from the resume text.
        
        Creates a clean, consistently formatted document with:
        - Professional header with name and contact info
        - Clear section headers with subtle styling
        - Consistent bullet formatting
        - Proper spacing and margins
        """
        from docx import Document
        from docx.shared import Pt, RGBColor, Inches, Twips
        from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_LINE_SPACING
        from docx.enum.style import WD_STYLE_TYPE
        from docx.oxml.ns import qn
        from docx.oxml import OxmlElement

        ats_text = self.to_ats_friendly_text(resume_text)
        doc = Document()
        
        # Set document margins
        for section in doc.sections:
            section.top_margin = Inches(0.6)
            section.bottom_margin = Inches(0.6)
            section.left_margin = Inches(0.75)
            section.right_margin = Inches(0.75)

        # Configure default Normal style
        style = doc.styles["Normal"]
        style.font.name = "Calibri"
        style.font.size = Pt(10.5)
        style.paragraph_format.space_after = Pt(0)
        style.paragraph_format.space_before = Pt(0)
        style.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE

        # Colors
        DARK_BLUE = RGBColor(0x1A, 0x36, 0x5D)  # Professional dark blue
        MEDIUM_BLUE = RGBColor(0x2B, 0x57, 0x9A)
        DARK_GRAY = RGBColor(0x33, 0x33, 0x33)
        LIGHT_GRAY = RGBColor(0x66, 0x66, 0x66)

        def _add_section_header(text: str):
            """Add a professional section header with bottom border."""
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(12)
            p.paragraph_format.space_after = Pt(4)
            run = p.add_run(text.upper())
            run.bold = True
            run.font.size = Pt(11)
            run.font.color.rgb = DARK_BLUE
            # Add bottom border
            pPr = p._p.get_or_add_pPr()
            pBdr = OxmlElement("w:pBdr")
            bottom = OxmlElement("w:bottom")
            bottom.set(qn("w:val"), "single")
            bottom.set(qn("w:sz"), "6")
            bottom.set(qn("w:color"), "1A365D")
            pBdr.append(bottom)
            pPr.append(pBdr)

        def _add_bullet_point(text: str):
            """Add a properly formatted bullet point."""
            p = doc.add_paragraph()
            p.paragraph_format.left_indent = Inches(0.25)
            p.paragraph_format.first_line_indent = Inches(-0.15)
            p.paragraph_format.space_after = Pt(2)
            run = p.add_run("• ")
            run.font.color.rgb = MEDIUM_BLUE
            content_run = p.add_run(text)
            content_run.font.color.rgb = DARK_GRAY

        def _add_body_text(text: str, is_contact: bool = False):
            """Add regular body text."""
            p = doc.add_paragraph()
            p.paragraph_format.space_after = Pt(2)
            if is_contact:
                p.alignment = WD_ALIGN_PARAGRAPH.CENTER
                run = p.add_run(text)
                run.font.size = Pt(10)
                run.font.color.rgb = LIGHT_GRAY
            else:
                run = p.add_run(text)
                run.font.color.rgb = DARK_GRAY

        # Parse lines
        lines = ats_text.splitlines()
        in_header = True
        header_lines_added = 0
        skip_next_blank = False

        for idx, line in enumerate(lines):
            stripped = line.strip()

            # Handle blank lines
            if not stripped:
                if skip_next_blank:
                    skip_next_blank = False
                    continue
                if in_header and header_lines_added > 0:
                    in_header = False
                    # Add a small spacer after header
                    spacer = doc.add_paragraph()
                    spacer.paragraph_format.space_after = Pt(4)
                continue

            # Detect section headers
            is_section_header = (
                len(stripped) <= 50
                and stripped == stripped.upper()
                and not stripped.startswith(("•", "-", "–", "*", "·"))
                and not stripped.endswith((",", ";", "."))
                and len(stripped.split()) <= 5
            )

            # First section header ends the header block
            if is_section_header and in_header:
                in_header = False

            # Handle header block (name, contact info)
            if in_header:
                if header_lines_added == 0:
                    # Name - large and centered
                    name_p = doc.add_paragraph()
                    name_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
                    name_p.paragraph_format.space_after = Pt(2)
                    name_run = name_p.add_run(stripped)
                    name_run.bold = True
                    name_run.font.size = Pt(18)
                    name_run.font.color.rgb = DARK_BLUE
                else:
                    # Contact info - smaller, centered, gray
                    _add_body_text(stripped, is_contact=True)
                header_lines_added += 1
                continue

            if is_section_header:
                _add_section_header(stripped)
                skip_next_blank = True
            elif stripped.startswith(("•", "-", "–", "*", "·")):
                bullet_text = stripped.lstrip("•-–*· ").strip()
                if bullet_text:
                    _add_bullet_point(bullet_text)
            else:
                _add_body_text(stripped)

        buf = io.BytesIO()
        doc.save(buf)
        return buf.getvalue()

    def generate_pdf(self, resume_text: str, candidate_name: str, job_title: str) -> bytes:
        """
        Generate a professional ATS-friendly PDF from the resume text.
        
        Creates a clean, consistently formatted document with:
        - Professional header with name and contact info
        - Clear section headers with subtle styling
        - Consistent bullet formatting
        - Proper spacing and margins
        """
        from reportlab.lib.pagesizes import A4, letter
        from reportlab.lib import colors
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import mm, inch
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, ListFlowable, ListItem
        from reportlab.lib.enums import TA_CENTER, TA_LEFT

        ats_text = self.to_ats_friendly_text(resume_text)
        
        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf,
            pagesize=letter,
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=0.6 * inch,
            bottomMargin=0.6 * inch,
        )

        # Professional colors
        DARK_BLUE = colors.HexColor("#1A365D")
        MEDIUM_BLUE = colors.HexColor("#2B579A")
        DARK_GRAY = colors.HexColor("#333333")
        LIGHT_GRAY = colors.HexColor("#666666")

        # Define styles
        name_style = ParagraphStyle(
            "Name", 
            fontSize=18, 
            fontName="Helvetica-Bold",
            alignment=TA_CENTER, 
            spaceAfter=2,
            textColor=DARK_BLUE
        )
        contact_style = ParagraphStyle(
            "Contact", 
            fontSize=10, 
            textColor=LIGHT_GRAY,
            alignment=TA_CENTER, 
            spaceAfter=4
        )
        section_style = ParagraphStyle(
            "Section", 
            fontSize=11, 
            fontName="Helvetica-Bold",
            textColor=DARK_BLUE, 
            spaceBefore=12, 
            spaceAfter=4
        )
        body_style = ParagraphStyle(
            "Body", 
            fontSize=10, 
            spaceAfter=3, 
            alignment=TA_LEFT,
            textColor=DARK_GRAY
        )
        bullet_style = ParagraphStyle(
            "Bullet", 
            fontSize=10, 
            leftIndent=15, 
            spaceAfter=2, 
            bulletIndent=5,
            textColor=DARK_GRAY
        )

        story = []
        lines = ats_text.splitlines()
        in_header = True
        header_lines_added = 0

        for idx, line in enumerate(lines):
            stripped = line.strip()

            # Handle blank lines
            if not stripped:
                if in_header and header_lines_added > 0:
                    in_header = False
                    story.append(Spacer(1, 8))
                else:
                    story.append(Spacer(1, 4))
                continue

            # Detect section headers
            is_section_header = (
                len(stripped) <= 50
                and stripped == stripped.upper()
                and not stripped.startswith(("•", "-", "–", "*", "·"))
                and not stripped.endswith((",", ";", "."))
                and len(stripped.split()) <= 5
            )

            # First section header ends header block
            if is_section_header and in_header:
                in_header = False

            # Handle header block (name, contact info)
            if in_header:
                if header_lines_added == 0:
                    story.append(Paragraph(stripped, name_style))
                else:
                    story.append(Paragraph(stripped, contact_style))
                header_lines_added += 1
                continue

            if is_section_header:
                story.append(Paragraph(stripped, section_style))
                story.append(HRFlowable(width="100%", thickness=1, color=DARK_BLUE, spaceAfter=4))
            elif stripped.startswith(("•", "-", "–", "*", "·")):
                content = stripped.lstrip("•-–*· ").strip()
                if content:
                    story.append(Paragraph(f"• {content}", bullet_style))
            else:
                story.append(Paragraph(stripped, body_style))

        doc.build(story)
        return buf.getvalue()


_optimizer_instance: Optional[ResumeOptimizerService] = None


def get_resume_optimizer() -> ResumeOptimizerService:
    global _optimizer_instance
    if _optimizer_instance is None:
        _optimizer_instance = ResumeOptimizerService()
    return _optimizer_instance
