"""
Resume Optimizer Service
========================
Uses the candidate's raw resume_text (extracted from their uploaded PDF/DOCX)
as the ONLY source of truth for AI optimization.

The structured resume_parsed_data is NOT used here — it is a display-only
representation generated by a separate AI parser and must not be treated as
the authoritative resume content.

Produces:
  - A list of text-level changes (verbatim original → improved replacement)
  - Before / After ATS score estimates
  - An optimized_text string (original resume_text with accepted changes applied)
  - Document exports (DOCX + PDF) generated from the optimized_text
"""
from __future__ import annotations

import io
import logging
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


class ResumeOptimizerService:
    """
    Orchestrates AI resume content optimization.

    Works exclusively on raw resume text. Never modifies formatting,
    layout, fonts, bullet styles, or spacing — only content.
    """

    def __init__(self):
        from app.services.ai.factory import get_ai
        self._ai = get_ai()

    # ------------------------------------------------------------------
    # Main optimization entry point
    # ------------------------------------------------------------------

    async def optimize(
        self,
        resume_text: str,
        job: Dict[str, Any],
        screening_analysis: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Analyze the raw resume text against the JD and return improvements.

        Args:
            resume_text:        The raw text extracted from the candidate's original
                                uploaded PDF/DOCX. This is the ONLY source used.
            job:                The job description dict (title, role, description,
                                must_have_skills, good_to_have_skills).
            screening_analysis: The ats_screenings row for gap context (optional).

        Returns:
            {
                optimization_summary: str,
                before_score: int,
                after_score: int,
                changes: [OptimizationChange],
                optimized_text: str  — full resume text with all changes applied
            }
        """
        from app.prompts.resume_optimization import get_resume_optimization_prompt
        import uuid

        what_lacks: List[str] = []
        whats_good: List[str] = []
        before_score = 0
        if isinstance(screening_analysis, dict):
            detailed = screening_analysis.get("detailed_analysis") or {}
            what_lacks = detailed.get("what_lacks") or []
            whats_good = detailed.get("whats_good") or []
            before_score = int(screening_analysis.get("overall_score") or 0)

        system_prompt, user_prompt = get_resume_optimization_prompt(
            resume_text=resume_text,
            job_title=job.get("title", ""),
            job_role=job.get("role", ""),
            job_description=job.get("description", ""),
            must_have_skills=job.get("must_have_skills") or [],
            good_to_have_skills=job.get("good_to_have_skills") or [],
            what_lacks=what_lacks,
            whats_good=whats_good,
            before_score=before_score,
            after_score_example=min(100, before_score + 12),
        )

        try:
            result = await self._ai.generate_json(
                user_prompt,
                system_instruction=system_prompt,
                temperature=0.35,
                max_tokens=6000,
                timeout_s=90,
            )
        except Exception as exc:
            logger.error("[ResumeOptimizer] AI call failed: %s", exc)
            raise RuntimeError("AI optimization failed. Please try again.") from exc

        # Normalize changes — assign UUIDs, validate verbatim originals
        changes = []
        gap_cautions = result.get("gap_cautions") or []
        for ch in result.get("changes") or []:
            if not isinstance(ch, dict):
                continue
            original = ch.get("original", "")
            improved = ch.get("improved", "")
            change_type = ch.get("change_type", "wording")

            # Gap cautions should be in gap_cautions array, but handle if AI puts them here
            if change_type == "gap_caution":
                gap_cautions.append({"reason": ch.get("reason", "")})
                continue

            # For all real changes: the original MUST be found verbatim in the resume.
            # We try exact match first, then whitespace-normalized match.
            if original:
                if original not in resume_text:
                    # Try normalizing whitespace in both
                    import re
                    norm_original = re.sub(r'\s+', ' ', original.strip())
                    norm_resume = re.sub(r'\s+', ' ', resume_text)
                    if norm_original not in norm_resume:
                        logger.warning(
                            "[ResumeOptimizer] Skipping change — original text not found in resume: %r",
                            original[:120],
                        )
                        continue
            else:
                # Empty original — skip (can't do a replacement without original)
                continue

            changes.append({
                "change_id": ch.get("change_id") or str(uuid.uuid4()),
                "section": ch.get("section", ""),
                "section_label": ch.get("section_label", ch.get("section", "").replace("_", " ").title()),
                "original": original,
                "improved": improved,
                "reason": ch.get("reason", ""),
                "change_type": change_type,
                "score_impact": int(ch.get("score_impact") or 0),
            })

        # Recalculate after_score from actual validated changes (never trust AI's after_score)
        total_impact = sum(c["score_impact"] for c in changes)
        computed_after_score = min(100, before_score + total_impact)

        # Build optimized_text (all changes applied to the original)
        optimized_text = self._apply_changes(resume_text, changes)

        return {
            "optimization_summary": result.get("optimization_summary", ""),
            "before_score": before_score,
            "after_score": computed_after_score,
            "changes": changes,
            "gap_cautions": gap_cautions,
            "optimized_text": optimized_text,
        }

    # ------------------------------------------------------------------
    # Apply a subset of changes to produce the final text
    # ------------------------------------------------------------------

    @staticmethod
    def apply_accepted_changes(resume_text: str, changes: List[Dict], accepted_ids: List[str]) -> str:
        """
        Apply only the accepted changes to the original resume text.
        Each change is a verbatim find-and-replace on the text.
        """
        accepted_set = set(accepted_ids)
        result = resume_text
        for ch in changes:
            if ch.get("change_id") not in accepted_set:
                continue
            original = ch.get("original", "")
            improved = ch.get("improved", "")
            change_type = ch.get("change_type", "")
            # Skip gap cautions and empty originals
            if change_type == "gap_caution" or not original or not improved:
                continue
            if original in result:
                result = result.replace(original, improved, 1)
        return result

    @staticmethod
    def _apply_changes(resume_text: str, changes: List[Dict]) -> str:
        """Apply ALL actionable changes to produce a fully optimized text."""
        result = resume_text
        for ch in changes:
            original = ch.get("original", "")
            improved = ch.get("improved", "")
            change_type = ch.get("change_type", "")
            if change_type == "gap_caution" or not original or not improved:
                continue
            if original in result:
                result = result.replace(original, improved, 1)
        return result

    # ------------------------------------------------------------------
    # Document generation — from plain text
    # ------------------------------------------------------------------

    async def generate_docx(
        self,
        resume_text: str,
        candidate_name: str,
        job_title: str,
        resume_url: Optional[str] = None,
        changes: Optional[List[Dict]] = None,
        accepted_ids: Optional[List[str]] = None
    ) -> bytes:
        """
        Generate a DOCX from the optimized (or original) resume text.

        If a resume_url is provided and it's a .docx file, we attempt to download
        it and modify it in-place using python-docx, preserving all styles.
        Otherwise, we generate a clean, standard DOCX from the text.
        """
        import io
        import httpx
        from docx import Document

        # 1. Attempt in-place modification if it's a DOCX
        if resume_url and resume_url.lower().endswith(".docx") and changes and accepted_ids is not None:
            try:
                async with httpx.AsyncClient() as client:
                    resp = await client.get(resume_url, timeout=10.0)
                if resp.status_code == 200:
                    doc_bytes = io.BytesIO(resp.content)
                    doc = Document(doc_bytes)

                    accepted_set = set(accepted_ids)
                    
                    # Iterate through accepted changes and do find/replace across paragraphs
                    for ch in changes:
                        if ch.get("change_id") not in accepted_set:
                            continue
                        
                        original = ch.get("original", "")
                        improved = ch.get("improved", "")
                        if not original or ch.get("change_type") == "missing_skill_notice":
                            continue

                        # Simple paragraph-level replacement for python-docx
                        # Note: This is a best-effort replacement. Text split across runs might not match,
                        # but often it works if the text is contiguous in a run, or we replace the paragraph text.
                        # For a robust replacement, we replace paragraph.text, which clears run-level formatting
                        # for that specific paragraph, but keeps paragraph styles.
                        for p in doc.paragraphs:
                            if original in p.text:
                                p.text = p.text.replace(original, improved)
                        
                        # Also check tables
                        for table in doc.tables:
                            for row in table.rows:
                                for cell in row.cells:
                                    for p in cell.paragraphs:
                                        if original in p.text:
                                            p.text = p.text.replace(original, improved)

                    out_buf = io.BytesIO()
                    doc.save(out_buf)
                    return out_buf.getvalue()
            except Exception as exc:
                logger.warning(f"Failed to modify DOCX in-place from {resume_url}: {exc}. Falling back to standard generation.")

        # 2. Fallback: Generate a standard template DOCX
        from docx.shared import Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.oxml.ns import qn
        from docx.oxml import OxmlElement

        doc = Document()

        # Set default style
        style = doc.styles["Normal"]
        style.font.name = "Calibri"
        style.font.size = Pt(11)

        def _add_section_divider(text: str):
            """Bold blue section header with bottom border."""
            p = doc.add_paragraph()
            run = p.add_run(text.upper())
            run.bold = True
            run.font.size = Pt(11)
            run.font.color.rgb = RGBColor(0x1E, 0x40, 0xAF)
            p.paragraph_format.space_before = Pt(10)
            p.paragraph_format.space_after = Pt(3)
            pPr = p._p.get_or_add_pPr()
            pBdr = OxmlElement("w:pBdr")
            bottom = OxmlElement("w:bottom")
            bottom.set(qn("w:val"), "single")
            bottom.set(qn("w:sz"), "4")
            bottom.set(qn("w:color"), "1E40AF")
            pBdr.append(bottom)
            pPr.append(pBdr)

        # Candidate name header
        name_p = doc.add_paragraph()
        name_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        name_run = name_p.add_run(candidate_name)
        name_run.bold = True
        name_run.font.size = Pt(20)

        doc.add_paragraph()

        # Parse the resume text into lines and render
        lines = resume_text.splitlines()
        for line in lines:
            stripped = line.strip()

            if not stripped:
                doc.add_paragraph()
                continue

            # Detect likely section headers
            is_section_header = (
                len(stripped) < 60
                and not stripped.startswith(("•", "-", "–", "*", "·"))
                and stripped == stripped.upper()
                and not stripped.endswith((",", ";", "."))
            )

            if is_section_header:
                _add_section_divider(stripped)
            elif stripped.startswith(("•", "-", "–", "*", "·")):
                # Bullet point
                p = doc.add_paragraph(style="List Bullet")
                p.add_run(stripped.lstrip("•-–*· ").strip())
            else:
                p = doc.add_paragraph()
                p.add_run(stripped)

        buf = io.BytesIO()
        doc.save(buf)
        return buf.getvalue()

    def generate_pdf(self, resume_text: str, candidate_name: str, job_title: str) -> bytes:
        """
        Generate a PDF from the optimized (or original) resume text using ReportLab.
        Preserves the natural structure of the resume text.
        """
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import mm
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
        from reportlab.lib.enums import TA_CENTER, TA_LEFT

        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf,
            pagesize=A4,
            rightMargin=20 * mm,
            leftMargin=20 * mm,
            topMargin=20 * mm,
            bottomMargin=20 * mm,
        )

        BLUE = colors.HexColor("#1E40AF")
        GREY = colors.HexColor("#6B7280")

        name_style = ParagraphStyle("Name", fontSize=22, fontName="Helvetica-Bold",
                                    alignment=TA_CENTER, spaceAfter=2)
        subtitle_style = ParagraphStyle("Subtitle", fontSize=9, textColor=GREY,
                                        alignment=TA_CENTER, spaceAfter=8)
        section_style = ParagraphStyle("Section", fontSize=11, fontName="Helvetica-Bold",
                                       textColor=BLUE, spaceBefore=12, spaceAfter=2)
        body_style = ParagraphStyle("Body", fontSize=10, spaceAfter=3, alignment=TA_LEFT)
        bullet_style = ParagraphStyle("Bullet", fontSize=10, leftIndent=12, spaceAfter=2, bulletIndent=4)

        story = []

        # Name
        story.append(Paragraph(candidate_name, name_style))
        story.append(Spacer(1, 6))

        lines = resume_text.splitlines()
        for line in lines:
            stripped = line.strip()

            if not stripped:
                story.append(Spacer(1, 4))
                continue

            is_section_header = (
                len(stripped) < 60
                and not stripped.startswith(("•", "-", "–", "*", "·"))
                and stripped == stripped.upper()
                and not stripped.endswith((",", ";", "."))
            )

            if is_section_header:
                story.append(Paragraph(stripped, section_style))
                story.append(HRFlowable(width="100%", thickness=1, color=BLUE, spaceAfter=3))
            elif stripped.startswith(("•", "-", "–", "*", "·")):
                content = stripped.lstrip("•-–*· ").strip()
                story.append(Paragraph(f"• {content}", bullet_style))
            else:
                story.append(Paragraph(stripped, body_style))

        doc.build(story)
        return buf.getvalue()


_optimizer_instance: Optional[ResumeOptimizerService] = None


def get_resume_optimizer() -> ResumeOptimizerService:
    global _optimizer_instance
    if _optimizer_instance is None:
        _optimizer_instance = ResumeOptimizerService()
    return _optimizer_instance
